/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWashesRouteImport } from './routes/api/washes'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiMachinesRouteImport } from './routes/api/machines'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AcompanharMachineIdRouteImport } from './routes/acompanhar/$machineId'
import { Route as ApiQrMachineIdRouteImport } from './routes/api/qr/$machineId'
import { Route as ApiMachinesMachineIdRouteImport } from './routes/api/machines/$machineId'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWashesRoute = ApiWashesRouteImport.update({
  id: '/api/washes',
  path: '/api/washes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachinesRoute = ApiMachinesRouteImport.update({
  id: '/api/machines',
  path: '/api/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharMachineIdRoute = AcompanharMachineIdRouteImport.update({
  id: '/acompanhar/$machineId',
  path: '/acompanhar/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrMachineIdRoute = ApiQrMachineIdRouteImport.update({
  id: '/api/qr/$machineId',
  path: '/api/qr/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachinesMachineIdRoute = ApiMachinesMachineIdRouteImport.update({
  id: '/$machineId',
  path: '/$machineId',
  getParentRoute: () => ApiMachinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/scan': typeof ScanRoute
  '/acompanhar/$machineId': typeof AcompanharMachineIdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/machines': typeof ApiMachinesRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/api/washes': typeof ApiWashesRoute
  '/api/machines/$machineId': typeof ApiMachinesMachineIdRoute
  '/api/qr/$machineId': typeof ApiQrMachineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/scan': typeof ScanRoute
  '/acompanhar/$machineId': typeof AcompanharMachineIdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/machines': typeof ApiMachinesRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/api/washes': typeof ApiWashesRoute
  '/api/machines/$machineId': typeof ApiMachinesMachineIdRoute
  '/api/qr/$machineId': typeof ApiQrMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/scan': typeof ScanRoute
  '/acompanhar/$machineId': typeof AcompanharMachineIdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/machines': typeof ApiMachinesRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/api/washes': typeof ApiWashesRoute
  '/api/machines/$machineId': typeof ApiMachinesMachineIdRoute
  '/api/qr/$machineId': typeof ApiQrMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/scan'
    | '/acompanhar/$machineId'
    | '/api/health'
    | '/api/machines'
    | '/api/session'
    | '/api/washes'
    | '/api/machines/$machineId'
    | '/api/qr/$machineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/scan'
    | '/acompanhar/$machineId'
    | '/api/health'
    | '/api/machines'
    | '/api/session'
    | '/api/washes'
    | '/api/machines/$machineId'
    | '/api/qr/$machineId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/scan'
    | '/acompanhar/$machineId'
    | '/api/health'
    | '/api/machines'
    | '/api/session'
    | '/api/washes'
    | '/api/machines/$machineId'
    | '/api/qr/$machineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ScanRoute: typeof ScanRoute
  AcompanharMachineIdRoute: typeof AcompanharMachineIdRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMachinesRoute: typeof ApiMachinesRouteWithChildren
  ApiSessionRoute: typeof ApiSessionRoute
  ApiWashesRoute: typeof ApiWashesRoute
  ApiQrMachineIdRoute: typeof ApiQrMachineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/washes': {
      id: '/api/washes'
      path: '/api/washes'
      fullPath: '/api/washes'
      preLoaderRoute: typeof ApiWashesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines': {
      id: '/api/machines'
      path: '/api/machines'
      fullPath: '/api/machines'
      preLoaderRoute: typeof ApiMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$machineId': {
      id: '/acompanhar/$machineId'
      path: '/acompanhar/$machineId'
      fullPath: '/acompanhar/$machineId'
      preLoaderRoute: typeof AcompanharMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr/$machineId': {
      id: '/api/qr/$machineId'
      path: '/api/qr/$machineId'
      fullPath: '/api/qr/$machineId'
      preLoaderRoute: typeof ApiQrMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines/$machineId': {
      id: '/api/machines/$machineId'
      path: '/$machineId'
      fullPath: '/api/machines/$machineId'
      preLoaderRoute: typeof ApiMachinesMachineIdRouteImport
      parentRoute: typeof ApiMachinesRoute
    }
  }
}

interface ApiMachinesRouteChildren {
  ApiMachinesMachineIdRoute: typeof ApiMachinesMachineIdRoute
}

const ApiMachinesRouteChildren: ApiMachinesRouteChildren = {
  ApiMachinesMachineIdRoute: ApiMachinesMachineIdRoute,
}

const ApiMachinesRouteWithChildren = ApiMachinesRoute._addFileChildren(
  ApiMachinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ScanRoute: ScanRoute,
  AcompanharMachineIdRoute: AcompanharMachineIdRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMachinesRoute: ApiMachinesRouteWithChildren,
  ApiSessionRoute: ApiSessionRoute,
  ApiWashesRoute: ApiWashesRoute,
  ApiQrMachineIdRoute: ApiQrMachineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
